name = "catsnotdoctors"
compatibility_date = "2024-04-24"

[build]
command = "pnpm build"

[build.upload]
format = "directory"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SESSION"
id = "c367b47d894543f3b04176abef5e7282"
preview_id = "a716d301f54a4d3ebad95a35b88ca95c"
