name = "catsnotdoctors"
compatibility_date = "2024-04-24"

# Explicitly set Pages configuration
[build]
command = "pnpm build"
pages_build_output_dir = "dist"

# Disable sessions/KV
[site]
no_sessions = true
